FROM node:16-alpine

WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json .
COPY package-lock.json .

# Install dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY . .

RUN npm run build

# Expose the port that the frontend will be running on
EXPOSE 3000

CMD ["npm", "start"]
