version: '3.7'

services:
  db:
    image: mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword