FROM python:3.9
WORKDIR /app

# Copy the requirements.txt file to the container
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the source code to the container
COPY src ./src

# Expose the port that the backend service will be running on
EXPOSE 8000

# Set the command to run the backend server
CMD ["python", "src/main.py"]